name: hello world
on:
  push:
    path:
      - '!docs/**'
    branchs:
      - 'main'
      - 'dev'
  pull_request:
    type: [opened, reopened, synchronize, labeled, unlabeled]
  workflow_dispatch:
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "TODAY=$(date + %y-%m-%d)" >> $GITHUB_ENV
      - run: echo Hello world, today is $TODAY
      - if: ${{github.event_name == 'pull_request'}}
        uses: mheap/spring-security-tutorial-labels@v1
        with:
          mode: exactly
